package com.sitorplay.app.data.settings

import android.content.SharedPreferences
import androidx.core.content.edit
import com.sitorplay.app.domain.model.EspnCredentials
import com.sitorplay.app.domain.model.LineupSettings
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import javax.inject.Inject
import javax.inject.Singleton

private const val KEY_SCORING_FORMAT = "scoring_format"
private const val KEY_SELECTED_TEAM_ID = "selected_team_id"
private const val NO_TEAM_SELECTED = -1L
private const val KEY_LINEUP_QB = "lineup_qb"
private const val KEY_LINEUP_RB = "lineup_rb"
private const val KEY_LINEUP_WR = "lineup_wr"
private const val KEY_LINEUP_TE = "lineup_te"
private const val KEY_LINEUP_FLEX = "lineup_flex"
private const val KEY_LINEUP_K = "lineup_k"
private const val KEY_LINEUP_DEF = "lineup_def"
private const val KEY_LOCK_REMINDERS_ENABLED = "lock_reminders_enabled"
private const val KEY_ESPN_LEAGUE_ID = "espn_league_id"
private const val KEY_ESPN_SEASON = "espn_season"
private const val KEY_MODEL_BUNDLE_URL = "model_bundle_url"

/** Small preference-backed settings shared across the app. */
@Singleton
class AppSettingsRepository @Inject constructor(
    private val preferences: SharedPreferences
) {
    private val _scoringFormat = MutableStateFlow(readScoringFormat())
    val scoringFormat: StateFlow<ScoringFormat> = _scoringFormat.asStateFlow()

    private val _selectedTeamId = MutableStateFlow(preferences.getLong(KEY_SELECTED_TEAM_ID, NO_TEAM_SELECTED))
    val selectedTeamId: StateFlow<Long> = _selectedTeamId.asStateFlow()

    private val _lineupSettings = MutableStateFlow(readLineupSettings())
    val lineupSettings: StateFlow<LineupSettings> = _lineupSettings.asStateFlow()

    private val _lockRemindersEnabled = MutableStateFlow(preferences.getBoolean(KEY_LOCK_REMINDERS_ENABLED, false))
    val lockRemindersEnabled: StateFlow<Boolean> = _lockRemindersEnabled.asStateFlow()

    private val _espnCredentials = MutableStateFlow(readEspnCredentials())
    val espnCredentials: StateFlow<EspnCredentials?> = _espnCredentials.asStateFlow()

    /**
     * Where to fetch the weekly feature bundle produced by `model/build_week.py`.
     *
     * Empty by default and deliberately not hardcoded: the file is generated by
     * whoever runs the pipeline and hosted wherever suits them, typically as a
     * release asset. With no URL the app simply falls back to the projection
     * heuristic instead of pointing at somewhere that may not exist.
     */
    private val _modelBundleUrl = MutableStateFlow(
        preferences.getString(KEY_MODEL_BUNDLE_URL, null).orEmpty()
    )
    val modelBundleUrl: StateFlow<String> = _modelBundleUrl.asStateFlow()

    fun setScoringFormat(format: ScoringFormat) {
        preferences.edit { putString(KEY_SCORING_FORMAT, format.name) }
        _scoringFormat.value = format
    }

    fun setSelectedTeam(teamId: Long) {
        preferences.edit { putLong(KEY_SELECTED_TEAM_ID, teamId) }
        _selectedTeamId.value = teamId
    }

    /** Called once at startup to fall back to [teamId] if nothing (or a deleted team) is selected. */
    fun ensureSelectedTeam(teamId: Long) {
        if (_selectedTeamId.value == NO_TEAM_SELECTED) {
            setSelectedTeam(teamId)
        }
    }

    fun setLineupSettings(settings: LineupSettings) {
        preferences.edit {
            putInt(KEY_LINEUP_QB, settings.qb)
            putInt(KEY_LINEUP_RB, settings.rb)
            putInt(KEY_LINEUP_WR, settings.wr)
            putInt(KEY_LINEUP_TE, settings.te)
            putInt(KEY_LINEUP_FLEX, settings.flex)
            putInt(KEY_LINEUP_K, settings.k)
            putInt(KEY_LINEUP_DEF, settings.def)
        }
        _lineupSettings.value = settings
    }

    fun setLockRemindersEnabled(enabled: Boolean) {
        preferences.edit { putBoolean(KEY_LOCK_REMINDERS_ENABLED, enabled) }
        _lockRemindersEnabled.value = enabled
    }

    /** Remembered so a re-import doesn't require retyping the league ID/season. */
    fun setEspnCredentials(credentials: EspnCredentials) {
        preferences.edit {
            putString(KEY_ESPN_LEAGUE_ID, credentials.leagueId)
            putString(KEY_ESPN_SEASON, credentials.season)
        }
        _espnCredentials.value = credentials
    }

    fun setModelBundleUrl(url: String) {
        val trimmed = url.trim()
        preferences.edit { putString(KEY_MODEL_BUNDLE_URL, trimmed) }
        _modelBundleUrl.value = trimmed
    }

    private fun readEspnCredentials(): EspnCredentials? {
        val leagueId = preferences.getString(KEY_ESPN_LEAGUE_ID, null) ?: return null
        val season = preferences.getString(KEY_ESPN_SEASON, null) ?: return null
        return EspnCredentials(leagueId, season)
    }

    private fun readScoringFormat(): ScoringFormat {
        val raw = preferences.getString(KEY_SCORING_FORMAT, null) ?: return ScoringFormat.PPR
        return runCatching { ScoringFormat.valueOf(raw) }.getOrDefault(ScoringFormat.PPR)
    }

    private fun readLineupSettings(): LineupSettings {
        val defaults = LineupSettings()
        return LineupSettings(
            qb = preferences.getInt(KEY_LINEUP_QB, defaults.qb),
            rb = preferences.getInt(KEY_LINEUP_RB, defaults.rb),
            wr = preferences.getInt(KEY_LINEUP_WR, defaults.wr),
            te = preferences.getInt(KEY_LINEUP_TE, defaults.te),
            flex = preferences.getInt(KEY_LINEUP_FLEX, defaults.flex),
            k = preferences.getInt(KEY_LINEUP_K, defaults.k),
            def = preferences.getInt(KEY_LINEUP_DEF, defaults.def)
        )
    }
}
